---

- hosts: localhost
  vars:
    nios_provider:
      host: 10.60.27.4
      username: admin
      password: infoblox
      wapi_version: 2.1

  connection: local
  tasks:
   - name: create zone
     nios_zone:
       name: ansiblezone.com
       view: ansibleDnsView
       grid_primary: 
         - name: apitest.blairlab
       grid_secondaries: 
         - name: apitest-cp.blairlab
       extattrs:
         Site: Test Site
       comment: Created with Ansible
       state: present
       provider: "{{ nios_provider }}"
