---

- hosts: localhost
  vars:
    nios_provider:
      host: 10.60.27.4
      username: admin
      password: infoblox

  connection: local
  tasks:
   - name: delete DNS view
     nios_dns_view:
       name: ansibleDnsView
       network_view: ansibleNetView
       state: absent
       provider: "{{ nios_provider }}"
