---

- hosts: localhost
  vars:
    nios_provider:
      host: 10.60.27.4
      username: admin
      password: infoblox

  connection: local
  tasks:
   - name: delete zone
     nios_zone:
       name: ansiblezone.com
       view: ansibleDnsView
       state: absent
       provider: "{{ nios_provider }}"
