---

- hosts: localhost
  vars:
    nios_provider:
      host: 10.60.27.4
      username: admin
      password: infoblox

  connection: local
  tasks:
   - name: delete network
     nios_network:
       network: 10.0.0.0/24
       network_view: ansibleNetView
       state: absent
       provider: "{{ nios_provider }}"
