---

- hosts: localhost
  vars:
    nios_provider:
      host: 10.60.27.4
      username: admin
      password: infoblox

  connection: local
  tasks:
   - name: delete network view
     nios_network_view:
       name: ansibleNetview
       state: absent
       provider: "{{ nios_provider }}"
