---
  
- hosts: localhost
  vars:
    nios_provider:
      host: hostname/hostip
      username: admin
      password: admin

  connection: local
  tasks:
   - name: Create Nios SRV record
     nios_srv_record:
       name: _sip._tcp.service.ansible.com
       port: 5080
       priority: 10
       target: service1.ansible.com
       weight: 10
       comment: Created with Ansible
       state: present
       provider: "{{ nios_provider }}"
