---

- hosts: localhost
  vars:
    nios_provider:
      host: 127.0.0.1
      username: cloud-admin
      password: infoblox
      wapi_version: 2.9

  connection: local
  tasks:
   - name: Create Infoblox member
     nios_member:
       host_name: member01.ansible-dev.com
       vip_setting:
         address: 192.168.1.100
         subnet_mask: 255.255.255.0
         gateway: 192.168.1.1
       config_addr_type: IPV4
       platform: VNIOS
       comment: Created with Ansible
       state: present
       provider: "{{ nios_provider }}"
